; Source: /home/artjom/Tools/llvm-project/llvm/test/Transforms/SLPVectorizer/RISCV/rvv-min-vector-size.ll
; Variant: riscv64_+v_slp-vectorizer
; Command: /home/artjom/Tools/llvm-project/build/bin/opt -passes=slp-vectorizer -mtriple=riscv64 -mattr=+v -riscv-v-vector-bits-min=128 -riscv-v-slp-max-vf=0 -S
; Original: RUN: opt < %s -passes=slp-vectorizer -mtriple=riscv64 -mattr=+v  -riscv-v-vector-bits-min=128 -riscv-v-slp-max-vf=0 -S | FileCheck %s --check-prefixes=CHECK,CHECK-128

; ======================================================================
; PRE-OPT (input IR)
; ======================================================================


target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n64-S128"
target triple = "riscv64"

define void @foo(ptr nocapture writeonly %da) {
entry:
  store i64 0, ptr %da, align 8
  %arrayidx1 = getelementptr inbounds i64, ptr %da, i64 1
  store i64 0, ptr %arrayidx1, align 8
  %arrayidx2 = getelementptr inbounds i64, ptr %da, i64 2
  store i64 0, ptr %arrayidx2, align 8
  %arrayidx3 = getelementptr inbounds i64, ptr %da, i64 3
  store i64 0, ptr %arrayidx3, align 8
  ret void
}

define void @foo8(ptr nocapture writeonly %da) {
entry:
  store i8 0, ptr %da, align 8
  %arrayidx1 = getelementptr inbounds i8, ptr %da, i8 1
  store i8 0, ptr %arrayidx1, align 8
  %arrayidx2 = getelementptr inbounds i8, ptr %da, i8 2
  ret void
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:

; ======================================================================
; POST-OPT (actual opt output)
; ======================================================================

; ModuleID = '/tmp/tmp4z8p9odj.ll'
source_filename = "/tmp/tmp4z8p9odj.ll"
target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n64-S128"
target triple = "riscv64"

define void @foo(ptr writeonly captures(none) %da) #0 {
entry:
  store <4 x i64> zeroinitializer, ptr %da, align 8
  ret void
}

define void @foo8(ptr writeonly captures(none) %da) #0 {
entry:
  store i8 0, ptr %da, align 8
  %arrayidx1 = getelementptr inbounds i8, ptr %da, i8 1
  store i8 0, ptr %arrayidx1, align 8
  %arrayidx2 = getelementptr inbounds i8, ptr %da, i8 2
  ret void
}

attributes #0 = { "target-features"="+v" }
