; Source: /home/artjom/Tools/llvm-project/llvm/test/Transforms/LoopVectorize/RISCV/partial-reduce-dot-product.ll
; Variant: +v_loop-vectorize_FIXED
; Command: /home/artjom/Tools/llvm-project/build/bin/opt -passes=loop-vectorize -mattr=+v -scalable-vectorization=off -tail-folding-policy=dont-fold-tail -S
; Original: RUN: opt -passes=loop-vectorize -mattr=+v -scalable-vectorization=off -tail-folding-policy=dont-fold-tail -S < %s | FileCheck %s --check-prefixes=FIXED,FIXED-V

; ======================================================================
; PRE-OPT (input IR)
; ======================================================================


; TODO: Remove -tail-folding-policy=dont-fold-tail when partial reductions with EVL tail folding is supported.

target triple = "riscv64-none-unknown-elf"

define i32 @vdot4a(ptr %a, ptr %b) #0 {
entry:
  br label %for.body

for.body:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.body ]
  %accum = phi i32 [ 0, %entry ], [ %add, %for.body ]
  %gep.a = getelementptr i8, ptr %a, i64 %iv
  %load.a = load i8, ptr %gep.a, align 1
  %ext.a = sext i8 %load.a to i32
  %gep.b = getelementptr i8, ptr %b, i64 %iv
  %load.b = load i8, ptr %gep.b, align 1
  %ext.b = sext i8 %load.b to i32
  %mul = mul i32 %ext.b, %ext.a
  %add = add i32 %mul, %accum
  %iv.next = add i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv.next, 1024
  br i1 %exitcond.not, label %for.exit, label %for.body

for.exit:
  ret i32 %add
}


define i32 @vdot4au(ptr %a, ptr %b) #0 {
entry:
  br label %for.body

for.body:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.body ]
  %accum = phi i32 [ 0, %entry ], [ %add, %for.body ]
  %gep.a = getelementptr i8, ptr %a, i64 %iv
  %load.a = load i8, ptr %gep.a, align 1
  %ext.a = zext i8 %load.a to i32
  %gep.b = getelementptr i8, ptr %b, i64 %iv
  %load.b = load i8, ptr %gep.b, align 1
  %ext.b = zext i8 %load.b to i32
  %mul = mul i32 %ext.b, %ext.a
  %add = add i32 %mul, %accum
  %iv.next = add i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv.next, 1024
  br i1 %exitcond.not, label %for.exit, label %for.body

for.exit:
  ret i32 %add
}


define i32 @vdot4asu(ptr %a, ptr %b) #0 {
entry:
  br label %for.body

for.body:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.body ]
  %accum = phi i32 [ 0, %entry ], [ %add, %for.body ]
  %gep.a = getelementptr i8, ptr %a, i64 %iv
  %load.a = load i8, ptr %gep.a, align 1
  %ext.a = zext i8 %load.a to i32
  %gep.b = getelementptr i8, ptr %b, i64 %iv
  %load.b = load i8, ptr %gep.b, align 1
  %ext.b = sext i8 %load.b to i32
  %mul = mul i32 %ext.b, %ext.a
  %add = add i32 %mul, %accum
  %iv.next = add i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv.next, 1024
  br i1 %exitcond.not, label %for.exit, label %for.body

for.exit:
  ret i32 %add
}

define i32 @vdot4asu2(ptr %a, ptr %b) #0 {
entry:
  br label %for.body

for.body:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.body ]
  %accum = phi i32 [ 0, %entry ], [ %add, %for.body ]
  %gep.a = getelementptr i8, ptr %a, i64 %iv
  %load.a = load i8, ptr %gep.a, align 1
  %ext.a = sext i8 %load.a to i32
  %gep.b = getelementptr i8, ptr %b, i64 %iv
  %load.b = load i8, ptr %gep.b, align 1
  %ext.b = zext i8 %load.b to i32
  %mul = mul i32 %ext.b, %ext.a
  %add = add i32 %mul, %accum
  %iv.next = add i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv.next, 1024
  br i1 %exitcond.not, label %for.exit, label %for.body

for.exit:
  ret i32 %add
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:

; ======================================================================
; POST-OPT (actual opt output)
; ======================================================================

; ModuleID = '/tmp/tmpysngh2eu.ll'
source_filename = "/tmp/tmpysngh2eu.ll"
target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n32:64-S128"
target triple = "riscv64-none-unknown-elf"

define i32 @vdot4a(ptr %a, ptr %b) #0 {
entry:
  br label %vector.ph

vector.ph:                                        ; preds = %entry
  br label %vector.body

vector.body:                                      ; preds = %vector.body, %vector.ph
  %index = phi i64 [ 0, %vector.ph ], [ %index.next, %vector.body ]
  %vec.phi = phi <8 x i32> [ zeroinitializer, %vector.ph ], [ %10, %vector.body ]
  %vec.phi1 = phi <8 x i32> [ zeroinitializer, %vector.ph ], [ %11, %vector.body ]
  %0 = getelementptr i8, ptr %a, i64 %index
  %1 = getelementptr i8, ptr %0, i64 8
  %wide.load = load <8 x i8>, ptr %0, align 1
  %wide.load2 = load <8 x i8>, ptr %1, align 1
  %2 = sext <8 x i8> %wide.load to <8 x i32>
  %3 = sext <8 x i8> %wide.load2 to <8 x i32>
  %4 = getelementptr i8, ptr %b, i64 %index
  %5 = getelementptr i8, ptr %4, i64 8
  %wide.load3 = load <8 x i8>, ptr %4, align 1
  %wide.load4 = load <8 x i8>, ptr %5, align 1
  %6 = sext <8 x i8> %wide.load3 to <8 x i32>
  %7 = sext <8 x i8> %wide.load4 to <8 x i32>
  %8 = mul <8 x i32> %6, %2
  %9 = mul <8 x i32> %7, %3
  %10 = add <8 x i32> %8, %vec.phi
  %11 = add <8 x i32> %9, %vec.phi1
  %index.next = add nuw i64 %index, 16
  %12 = icmp eq i64 %index.next, 1024
  br i1 %12, label %middle.block, label %vector.body, !llvm.loop !0

middle.block:                                     ; preds = %vector.body
  %bin.rdx = add <8 x i32> %11, %10
  %13 = call i32 @llvm.vector.reduce.add.v8i32(<8 x i32> %bin.rdx)
  br label %for.exit

for.exit:                                         ; preds = %middle.block
  ret i32 %13
}

define i32 @vdot4au(ptr %a, ptr %b) #0 {
entry:
  br label %vector.ph

vector.ph:                                        ; preds = %entry
  br label %vector.body

vector.body:                                      ; preds = %vector.body, %vector.ph
  %index = phi i64 [ 0, %vector.ph ], [ %index.next, %vector.body ]
  %vec.phi = phi <8 x i32> [ zeroinitializer, %vector.ph ], [ %10, %vector.body ]
  %vec.phi1 = phi <8 x i32> [ zeroinitializer, %vector.ph ], [ %11, %vector.body ]
  %0 = getelementptr i8, ptr %a, i64 %index
  %1 = getelementptr i8, ptr %0, i64 8
  %wide.load = load <8 x i8>, ptr %0, align 1
  %wide.load2 = load <8 x i8>, ptr %1, align 1
  %2 = zext <8 x i8> %wide.load to <8 x i32>
  %3 = zext <8 x i8> %wide.load2 to <8 x i32>
  %4 = getelementptr i8, ptr %b, i64 %index
  %5 = getelementptr i8, ptr %4, i64 8
  %wide.load3 = load <8 x i8>, ptr %4, align 1
  %wide.load4 = load <8 x i8>, ptr %5, align 1
  %6 = zext <8 x i8> %wide.load3 to <8 x i32>
  %7 = zext <8 x i8> %wide.load4 to <8 x i32>
  %8 = mul <8 x i32> %6, %2
  %9 = mul <8 x i32> %7, %3
  %10 = add <8 x i32> %8, %vec.phi
  %11 = add <8 x i32> %9, %vec.phi1
  %index.next = add nuw i64 %index, 16
  %12 = icmp eq i64 %index.next, 1024
  br i1 %12, label %middle.block, label %vector.body, !llvm.loop !3

middle.block:                                     ; preds = %vector.body
  %bin.rdx = add <8 x i32> %11, %10
  %13 = call i32 @llvm.vector.reduce.add.v8i32(<8 x i32> %bin.rdx)
  br label %for.exit

for.exit:                                         ; preds = %middle.block
  ret i32 %13
}

define i32 @vdot4asu(ptr %a, ptr %b) #0 {
entry:
  br label %vector.ph

vector.ph:                                        ; preds = %entry
  br label %vector.body

vector.body:                                      ; preds = %vector.body, %vector.ph
  %index = phi i64 [ 0, %vector.ph ], [ %index.next, %vector.body ]
  %vec.phi = phi <8 x i32> [ zeroinitializer, %vector.ph ], [ %10, %vector.body ]
  %vec.phi1 = phi <8 x i32> [ zeroinitializer, %vector.ph ], [ %11, %vector.body ]
  %0 = getelementptr i8, ptr %a, i64 %index
  %1 = getelementptr i8, ptr %0, i64 8
  %wide.load = load <8 x i8>, ptr %0, align 1
  %wide.load2 = load <8 x i8>, ptr %1, align 1
  %2 = zext <8 x i8> %wide.load to <8 x i32>
  %3 = zext <8 x i8> %wide.load2 to <8 x i32>
  %4 = getelementptr i8, ptr %b, i64 %index
  %5 = getelementptr i8, ptr %4, i64 8
  %wide.load3 = load <8 x i8>, ptr %4, align 1
  %wide.load4 = load <8 x i8>, ptr %5, align 1
  %6 = sext <8 x i8> %wide.load3 to <8 x i32>
  %7 = sext <8 x i8> %wide.load4 to <8 x i32>
  %8 = mul <8 x i32> %6, %2
  %9 = mul <8 x i32> %7, %3
  %10 = add <8 x i32> %8, %vec.phi
  %11 = add <8 x i32> %9, %vec.phi1
  %index.next = add nuw i64 %index, 16
  %12 = icmp eq i64 %index.next, 1024
  br i1 %12, label %middle.block, label %vector.body, !llvm.loop !4

middle.block:                                     ; preds = %vector.body
  %bin.rdx = add <8 x i32> %11, %10
  %13 = call i32 @llvm.vector.reduce.add.v8i32(<8 x i32> %bin.rdx)
  br label %for.exit

for.exit:                                         ; preds = %middle.block
  ret i32 %13
}

define i32 @vdot4asu2(ptr %a, ptr %b) #0 {
entry:
  br label %vector.ph

vector.ph:                                        ; preds = %entry
  br label %vector.body

vector.body:                                      ; preds = %vector.body, %vector.ph
  %index = phi i64 [ 0, %vector.ph ], [ %index.next, %vector.body ]
  %vec.phi = phi <8 x i32> [ zeroinitializer, %vector.ph ], [ %10, %vector.body ]
  %vec.phi1 = phi <8 x i32> [ zeroinitializer, %vector.ph ], [ %11, %vector.body ]
  %0 = getelementptr i8, ptr %a, i64 %index
  %1 = getelementptr i8, ptr %0, i64 8
  %wide.load = load <8 x i8>, ptr %0, align 1
  %wide.load2 = load <8 x i8>, ptr %1, align 1
  %2 = sext <8 x i8> %wide.load to <8 x i32>
  %3 = sext <8 x i8> %wide.load2 to <8 x i32>
  %4 = getelementptr i8, ptr %b, i64 %index
  %5 = getelementptr i8, ptr %4, i64 8
  %wide.load3 = load <8 x i8>, ptr %4, align 1
  %wide.load4 = load <8 x i8>, ptr %5, align 1
  %6 = zext <8 x i8> %wide.load3 to <8 x i32>
  %7 = zext <8 x i8> %wide.load4 to <8 x i32>
  %8 = mul <8 x i32> %6, %2
  %9 = mul <8 x i32> %7, %3
  %10 = add <8 x i32> %8, %vec.phi
  %11 = add <8 x i32> %9, %vec.phi1
  %index.next = add nuw i64 %index, 16
  %12 = icmp eq i64 %index.next, 1024
  br i1 %12, label %middle.block, label %vector.body, !llvm.loop !5

middle.block:                                     ; preds = %vector.body
  %bin.rdx = add <8 x i32> %11, %10
  %13 = call i32 @llvm.vector.reduce.add.v8i32(<8 x i32> %bin.rdx)
  br label %for.exit

for.exit:                                         ; preds = %middle.block
  ret i32 %13
}

; Function Attrs: nocallback nocreateundeforpoison nofree nosync nounwind speculatable willreturn memory(none)
declare i32 @llvm.vector.reduce.add.v8i32(<8 x i32>) #1

attributes #0 = { "target-features"="+v" }
attributes #1 = { nocallback nocreateundeforpoison nofree nosync nounwind speculatable willreturn memory(none) }

!0 = distinct !{!0, !1, !2}
!1 = !{!"llvm.loop.isvectorized", i32 1}
!2 = !{!"llvm.loop.unroll.runtime.disable"}
!3 = distinct !{!3, !1, !2}
!4 = distinct !{!4, !1, !2}
!5 = distinct !{!5, !1, !2}
