; Source: /home/artjom/Tools/llvm-project/llvm/test/Transforms/LoopVectorize/RISCV/partial-reduce-dot-product.ll
; Variant: +v,+experimental-zvdot4a8i_loop-vectorize_FIXED
; Command: /home/artjom/Tools/llvm-project/build/bin/opt -passes=loop-vectorize -mattr=+v,+experimental-zvdot4a8i -scalable-vectorization=off -tail-folding-policy=dont-fold-tail -S
; Original: RUN: opt -passes=loop-vectorize -mattr=+v,+experimental-zvdot4a8i -scalable-vectorization=off -tail-folding-policy=dont-fold-tail -S < %s | FileCheck %s --check-prefixes=FIXED,FIXED-ZVDOT4A8I

; ======================================================================
; PRE-OPT (input IR)
; ======================================================================


; TODO: Remove -tail-folding-policy=dont-fold-tail when partial reductions with EVL tail folding is supported.

target triple = "riscv64-none-unknown-elf"

define i32 @vdot4a(ptr %a, ptr %b) #0 {
entry:
  br label %for.body

for.body:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.body ]
  %accum = phi i32 [ 0, %entry ], [ %add, %for.body ]
  %gep.a = getelementptr i8, ptr %a, i64 %iv
  %load.a = load i8, ptr %gep.a, align 1
  %ext.a = sext i8 %load.a to i32
  %gep.b = getelementptr i8, ptr %b, i64 %iv
  %load.b = load i8, ptr %gep.b, align 1
  %ext.b = sext i8 %load.b to i32
  %mul = mul i32 %ext.b, %ext.a
  %add = add i32 %mul, %accum
  %iv.next = add i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv.next, 1024
  br i1 %exitcond.not, label %for.exit, label %for.body

for.exit:
  ret i32 %add
}


define i32 @vdot4au(ptr %a, ptr %b) #0 {
entry:
  br label %for.body

for.body:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.body ]
  %accum = phi i32 [ 0, %entry ], [ %add, %for.body ]
  %gep.a = getelementptr i8, ptr %a, i64 %iv
  %load.a = load i8, ptr %gep.a, align 1
  %ext.a = zext i8 %load.a to i32
  %gep.b = getelementptr i8, ptr %b, i64 %iv
  %load.b = load i8, ptr %gep.b, align 1
  %ext.b = zext i8 %load.b to i32
  %mul = mul i32 %ext.b, %ext.a
  %add = add i32 %mul, %accum
  %iv.next = add i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv.next, 1024
  br i1 %exitcond.not, label %for.exit, label %for.body

for.exit:
  ret i32 %add
}


define i32 @vdot4asu(ptr %a, ptr %b) #0 {
entry:
  br label %for.body

for.body:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.body ]
  %accum = phi i32 [ 0, %entry ], [ %add, %for.body ]
  %gep.a = getelementptr i8, ptr %a, i64 %iv
  %load.a = load i8, ptr %gep.a, align 1
  %ext.a = zext i8 %load.a to i32
  %gep.b = getelementptr i8, ptr %b, i64 %iv
  %load.b = load i8, ptr %gep.b, align 1
  %ext.b = sext i8 %load.b to i32
  %mul = mul i32 %ext.b, %ext.a
  %add = add i32 %mul, %accum
  %iv.next = add i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv.next, 1024
  br i1 %exitcond.not, label %for.exit, label %for.body

for.exit:
  ret i32 %add
}

define i32 @vdot4asu2(ptr %a, ptr %b) #0 {
entry:
  br label %for.body

for.body:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.body ]
  %accum = phi i32 [ 0, %entry ], [ %add, %for.body ]
  %gep.a = getelementptr i8, ptr %a, i64 %iv
  %load.a = load i8, ptr %gep.a, align 1
  %ext.a = sext i8 %load.a to i32
  %gep.b = getelementptr i8, ptr %b, i64 %iv
  %load.b = load i8, ptr %gep.b, align 1
  %ext.b = zext i8 %load.b to i32
  %mul = mul i32 %ext.b, %ext.a
  %add = add i32 %mul, %accum
  %iv.next = add i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv.next, 1024
  br i1 %exitcond.not, label %for.exit, label %for.body

for.exit:
  ret i32 %add
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:

; ======================================================================
; POST-OPT (actual opt output)
; ======================================================================

; ModuleID = '/tmp/tmpu9xwpmmm.ll'
source_filename = "/tmp/tmpu9xwpmmm.ll"
target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n32:64-S128"
target triple = "riscv64-none-unknown-elf"

define i32 @vdot4a(ptr %a, ptr %b) #0 {
entry:
  br label %vector.ph

vector.ph:                                        ; preds = %entry
  br label %vector.body

vector.body:                                      ; preds = %vector.body, %vector.ph
  %index = phi i64 [ 0, %vector.ph ], [ %index.next, %vector.body ]
  %vec.phi = phi <2 x i32> [ zeroinitializer, %vector.ph ], [ %partial.reduce, %vector.body ]
  %vec.phi1 = phi <2 x i32> [ zeroinitializer, %vector.ph ], [ %partial.reduce5, %vector.body ]
  %0 = getelementptr i8, ptr %a, i64 %index
  %1 = getelementptr i8, ptr %0, i64 8
  %wide.load = load <8 x i8>, ptr %0, align 1
  %wide.load2 = load <8 x i8>, ptr %1, align 1
  %2 = getelementptr i8, ptr %b, i64 %index
  %3 = getelementptr i8, ptr %2, i64 8
  %wide.load3 = load <8 x i8>, ptr %2, align 1
  %wide.load4 = load <8 x i8>, ptr %3, align 1
  %4 = sext <8 x i8> %wide.load3 to <8 x i32>
  %5 = sext <8 x i8> %wide.load to <8 x i32>
  %6 = mul <8 x i32> %4, %5
  %partial.reduce = call <2 x i32> @llvm.vector.partial.reduce.add.v2i32.v8i32(<2 x i32> %vec.phi, <8 x i32> %6)
  %7 = sext <8 x i8> %wide.load4 to <8 x i32>
  %8 = sext <8 x i8> %wide.load2 to <8 x i32>
  %9 = mul <8 x i32> %7, %8
  %partial.reduce5 = call <2 x i32> @llvm.vector.partial.reduce.add.v2i32.v8i32(<2 x i32> %vec.phi1, <8 x i32> %9)
  %index.next = add nuw i64 %index, 16
  %10 = icmp eq i64 %index.next, 1024
  br i1 %10, label %middle.block, label %vector.body, !llvm.loop !0

middle.block:                                     ; preds = %vector.body
  %bin.rdx = add <2 x i32> %partial.reduce5, %partial.reduce
  %11 = call i32 @llvm.vector.reduce.add.v2i32(<2 x i32> %bin.rdx)
  br label %for.exit

for.exit:                                         ; preds = %middle.block
  ret i32 %11
}

define i32 @vdot4au(ptr %a, ptr %b) #0 {
entry:
  br label %vector.ph

vector.ph:                                        ; preds = %entry
  br label %vector.body

vector.body:                                      ; preds = %vector.body, %vector.ph
  %index = phi i64 [ 0, %vector.ph ], [ %index.next, %vector.body ]
  %vec.phi = phi <2 x i32> [ zeroinitializer, %vector.ph ], [ %partial.reduce, %vector.body ]
  %vec.phi1 = phi <2 x i32> [ zeroinitializer, %vector.ph ], [ %partial.reduce5, %vector.body ]
  %0 = getelementptr i8, ptr %a, i64 %index
  %1 = getelementptr i8, ptr %0, i64 8
  %wide.load = load <8 x i8>, ptr %0, align 1
  %wide.load2 = load <8 x i8>, ptr %1, align 1
  %2 = getelementptr i8, ptr %b, i64 %index
  %3 = getelementptr i8, ptr %2, i64 8
  %wide.load3 = load <8 x i8>, ptr %2, align 1
  %wide.load4 = load <8 x i8>, ptr %3, align 1
  %4 = zext <8 x i8> %wide.load3 to <8 x i32>
  %5 = zext <8 x i8> %wide.load to <8 x i32>
  %6 = mul <8 x i32> %4, %5
  %partial.reduce = call <2 x i32> @llvm.vector.partial.reduce.add.v2i32.v8i32(<2 x i32> %vec.phi, <8 x i32> %6)
  %7 = zext <8 x i8> %wide.load4 to <8 x i32>
  %8 = zext <8 x i8> %wide.load2 to <8 x i32>
  %9 = mul <8 x i32> %7, %8
  %partial.reduce5 = call <2 x i32> @llvm.vector.partial.reduce.add.v2i32.v8i32(<2 x i32> %vec.phi1, <8 x i32> %9)
  %index.next = add nuw i64 %index, 16
  %10 = icmp eq i64 %index.next, 1024
  br i1 %10, label %middle.block, label %vector.body, !llvm.loop !3

middle.block:                                     ; preds = %vector.body
  %bin.rdx = add <2 x i32> %partial.reduce5, %partial.reduce
  %11 = call i32 @llvm.vector.reduce.add.v2i32(<2 x i32> %bin.rdx)
  br label %for.exit

for.exit:                                         ; preds = %middle.block
  ret i32 %11
}

define i32 @vdot4asu(ptr %a, ptr %b) #0 {
entry:
  br label %vector.ph

vector.ph:                                        ; preds = %entry
  br label %vector.body

vector.body:                                      ; preds = %vector.body, %vector.ph
  %index = phi i64 [ 0, %vector.ph ], [ %index.next, %vector.body ]
  %vec.phi = phi <2 x i32> [ zeroinitializer, %vector.ph ], [ %partial.reduce, %vector.body ]
  %vec.phi1 = phi <2 x i32> [ zeroinitializer, %vector.ph ], [ %partial.reduce5, %vector.body ]
  %0 = getelementptr i8, ptr %a, i64 %index
  %1 = getelementptr i8, ptr %0, i64 8
  %wide.load = load <8 x i8>, ptr %0, align 1
  %wide.load2 = load <8 x i8>, ptr %1, align 1
  %2 = getelementptr i8, ptr %b, i64 %index
  %3 = getelementptr i8, ptr %2, i64 8
  %wide.load3 = load <8 x i8>, ptr %2, align 1
  %wide.load4 = load <8 x i8>, ptr %3, align 1
  %4 = sext <8 x i8> %wide.load3 to <8 x i32>
  %5 = zext <8 x i8> %wide.load to <8 x i32>
  %6 = mul <8 x i32> %4, %5
  %partial.reduce = call <2 x i32> @llvm.vector.partial.reduce.add.v2i32.v8i32(<2 x i32> %vec.phi, <8 x i32> %6)
  %7 = sext <8 x i8> %wide.load4 to <8 x i32>
  %8 = zext <8 x i8> %wide.load2 to <8 x i32>
  %9 = mul <8 x i32> %7, %8
  %partial.reduce5 = call <2 x i32> @llvm.vector.partial.reduce.add.v2i32.v8i32(<2 x i32> %vec.phi1, <8 x i32> %9)
  %index.next = add nuw i64 %index, 16
  %10 = icmp eq i64 %index.next, 1024
  br i1 %10, label %middle.block, label %vector.body, !llvm.loop !4

middle.block:                                     ; preds = %vector.body
  %bin.rdx = add <2 x i32> %partial.reduce5, %partial.reduce
  %11 = call i32 @llvm.vector.reduce.add.v2i32(<2 x i32> %bin.rdx)
  br label %for.exit

for.exit:                                         ; preds = %middle.block
  ret i32 %11
}

define i32 @vdot4asu2(ptr %a, ptr %b) #0 {
entry:
  br label %vector.ph

vector.ph:                                        ; preds = %entry
  br label %vector.body

vector.body:                                      ; preds = %vector.body, %vector.ph
  %index = phi i64 [ 0, %vector.ph ], [ %index.next, %vector.body ]
  %vec.phi = phi <2 x i32> [ zeroinitializer, %vector.ph ], [ %partial.reduce, %vector.body ]
  %vec.phi1 = phi <2 x i32> [ zeroinitializer, %vector.ph ], [ %partial.reduce5, %vector.body ]
  %0 = getelementptr i8, ptr %a, i64 %index
  %1 = getelementptr i8, ptr %0, i64 8
  %wide.load = load <8 x i8>, ptr %0, align 1
  %wide.load2 = load <8 x i8>, ptr %1, align 1
  %2 = getelementptr i8, ptr %b, i64 %index
  %3 = getelementptr i8, ptr %2, i64 8
  %wide.load3 = load <8 x i8>, ptr %2, align 1
  %wide.load4 = load <8 x i8>, ptr %3, align 1
  %4 = zext <8 x i8> %wide.load3 to <8 x i32>
  %5 = sext <8 x i8> %wide.load to <8 x i32>
  %6 = mul <8 x i32> %4, %5
  %partial.reduce = call <2 x i32> @llvm.vector.partial.reduce.add.v2i32.v8i32(<2 x i32> %vec.phi, <8 x i32> %6)
  %7 = zext <8 x i8> %wide.load4 to <8 x i32>
  %8 = sext <8 x i8> %wide.load2 to <8 x i32>
  %9 = mul <8 x i32> %7, %8
  %partial.reduce5 = call <2 x i32> @llvm.vector.partial.reduce.add.v2i32.v8i32(<2 x i32> %vec.phi1, <8 x i32> %9)
  %index.next = add nuw i64 %index, 16
  %10 = icmp eq i64 %index.next, 1024
  br i1 %10, label %middle.block, label %vector.body, !llvm.loop !5

middle.block:                                     ; preds = %vector.body
  %bin.rdx = add <2 x i32> %partial.reduce5, %partial.reduce
  %11 = call i32 @llvm.vector.reduce.add.v2i32(<2 x i32> %bin.rdx)
  br label %for.exit

for.exit:                                         ; preds = %middle.block
  ret i32 %11
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare <2 x i32> @llvm.vector.partial.reduce.add.v2i32.v8i32(<2 x i32>, <8 x i32>) #1

; Function Attrs: nocallback nocreateundeforpoison nofree nosync nounwind speculatable willreturn memory(none)
declare i32 @llvm.vector.reduce.add.v2i32(<2 x i32>) #2

attributes #0 = { "target-features"="+v,+experimental-zvdot4a8i" }
attributes #1 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
attributes #2 = { nocallback nocreateundeforpoison nofree nosync nounwind speculatable willreturn memory(none) }

!0 = distinct !{!0, !1, !2}
!1 = !{!"llvm.loop.isvectorized", i32 1}
!2 = !{!"llvm.loop.unroll.runtime.disable"}
!3 = distinct !{!3, !1, !2}
!4 = distinct !{!4, !1, !2}
!5 = distinct !{!5, !1, !2}
