; Source: /home/artjom/Tools/llvm-project/llvm/test/Transforms/LoopVectorize/RISCV/partial-reduce-dot-product.ll
; Variant: +v,+experimental-zvdot4a8i_loop-vectorize_1
; Command: /home/artjom/Tools/llvm-project/build/bin/opt -passes=loop-vectorize -mattr=+v,+experimental-zvdot4a8i -S
; Original: RUN: opt -passes=loop-vectorize -mattr=+v,+experimental-zvdot4a8i -S < %s | FileCheck %s --check-prefixes=CHECK,TAILFOLD

; ======================================================================
; PRE-OPT (input IR)
; ======================================================================


; TODO: Remove -tail-folding-policy=dont-fold-tail when partial reductions with EVL tail folding is supported.

target triple = "riscv64-none-unknown-elf"

define i32 @vdot4a(ptr %a, ptr %b) #0 {
entry:
  br label %for.body

for.body:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.body ]
  %accum = phi i32 [ 0, %entry ], [ %add, %for.body ]
  %gep.a = getelementptr i8, ptr %a, i64 %iv
  %load.a = load i8, ptr %gep.a, align 1
  %ext.a = sext i8 %load.a to i32
  %gep.b = getelementptr i8, ptr %b, i64 %iv
  %load.b = load i8, ptr %gep.b, align 1
  %ext.b = sext i8 %load.b to i32
  %mul = mul i32 %ext.b, %ext.a
  %add = add i32 %mul, %accum
  %iv.next = add i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv.next, 1024
  br i1 %exitcond.not, label %for.exit, label %for.body

for.exit:
  ret i32 %add
}


define i32 @vdot4au(ptr %a, ptr %b) #0 {
entry:
  br label %for.body

for.body:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.body ]
  %accum = phi i32 [ 0, %entry ], [ %add, %for.body ]
  %gep.a = getelementptr i8, ptr %a, i64 %iv
  %load.a = load i8, ptr %gep.a, align 1
  %ext.a = zext i8 %load.a to i32
  %gep.b = getelementptr i8, ptr %b, i64 %iv
  %load.b = load i8, ptr %gep.b, align 1
  %ext.b = zext i8 %load.b to i32
  %mul = mul i32 %ext.b, %ext.a
  %add = add i32 %mul, %accum
  %iv.next = add i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv.next, 1024
  br i1 %exitcond.not, label %for.exit, label %for.body

for.exit:
  ret i32 %add
}


define i32 @vdot4asu(ptr %a, ptr %b) #0 {
entry:
  br label %for.body

for.body:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.body ]
  %accum = phi i32 [ 0, %entry ], [ %add, %for.body ]
  %gep.a = getelementptr i8, ptr %a, i64 %iv
  %load.a = load i8, ptr %gep.a, align 1
  %ext.a = zext i8 %load.a to i32
  %gep.b = getelementptr i8, ptr %b, i64 %iv
  %load.b = load i8, ptr %gep.b, align 1
  %ext.b = sext i8 %load.b to i32
  %mul = mul i32 %ext.b, %ext.a
  %add = add i32 %mul, %accum
  %iv.next = add i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv.next, 1024
  br i1 %exitcond.not, label %for.exit, label %for.body

for.exit:
  ret i32 %add
}

define i32 @vdot4asu2(ptr %a, ptr %b) #0 {
entry:
  br label %for.body

for.body:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.body ]
  %accum = phi i32 [ 0, %entry ], [ %add, %for.body ]
  %gep.a = getelementptr i8, ptr %a, i64 %iv
  %load.a = load i8, ptr %gep.a, align 1
  %ext.a = sext i8 %load.a to i32
  %gep.b = getelementptr i8, ptr %b, i64 %iv
  %load.b = load i8, ptr %gep.b, align 1
  %ext.b = zext i8 %load.b to i32
  %mul = mul i32 %ext.b, %ext.a
  %add = add i32 %mul, %accum
  %iv.next = add i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv.next, 1024
  br i1 %exitcond.not, label %for.exit, label %for.body

for.exit:
  ret i32 %add
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:

; ======================================================================
; POST-OPT (actual opt output)
; ======================================================================

; ModuleID = '/tmp/tmpr8i26d5x.ll'
source_filename = "/tmp/tmpr8i26d5x.ll"
target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n32:64-S128"
target triple = "riscv64-none-unknown-elf"

define i32 @vdot4a(ptr %a, ptr %b) #0 {
entry:
  br label %vector.ph

vector.ph:                                        ; preds = %entry
  br label %vector.body

vector.body:                                      ; preds = %vector.body, %vector.ph
  %index = phi i64 [ 0, %vector.ph ], [ %current.iteration.next, %vector.body ]
  %vec.phi = phi <vscale x 4 x i32> [ zeroinitializer, %vector.ph ], [ %7, %vector.body ]
  %avl = phi i64 [ 1024, %vector.ph ], [ %avl.next, %vector.body ]
  %0 = call i32 @llvm.experimental.get.vector.length.i64(i64 %avl, i32 4, i1 true)
  %1 = getelementptr i8, ptr %a, i64 %index
  %vp.op.load = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 %1, <vscale x 4 x i1> splat (i1 true), i32 %0)
  %2 = sext <vscale x 4 x i8> %vp.op.load to <vscale x 4 x i32>
  %3 = getelementptr i8, ptr %b, i64 %index
  %vp.op.load1 = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 %3, <vscale x 4 x i1> splat (i1 true), i32 %0)
  %4 = sext <vscale x 4 x i8> %vp.op.load1 to <vscale x 4 x i32>
  %5 = mul <vscale x 4 x i32> %4, %2
  %6 = add <vscale x 4 x i32> %5, %vec.phi
  %7 = call <vscale x 4 x i32> @llvm.vp.merge.nxv4i32(<vscale x 4 x i1> splat (i1 true), <vscale x 4 x i32> %6, <vscale x 4 x i32> %vec.phi, i32 %0)
  %8 = zext i32 %0 to i64
  %current.iteration.next = add nuw i64 %8, %index
  %avl.next = sub nuw i64 %avl, %8
  %9 = icmp eq i64 %avl.next, 0
  br i1 %9, label %middle.block, label %vector.body, !llvm.loop !0

middle.block:                                     ; preds = %vector.body
  %10 = call i32 @llvm.vector.reduce.add.nxv4i32(<vscale x 4 x i32> %7)
  br label %for.exit

for.exit:                                         ; preds = %middle.block
  ret i32 %10
}

define i32 @vdot4au(ptr %a, ptr %b) #0 {
entry:
  br label %vector.ph

vector.ph:                                        ; preds = %entry
  br label %vector.body

vector.body:                                      ; preds = %vector.body, %vector.ph
  %index = phi i64 [ 0, %vector.ph ], [ %current.iteration.next, %vector.body ]
  %vec.phi = phi <vscale x 4 x i32> [ zeroinitializer, %vector.ph ], [ %7, %vector.body ]
  %avl = phi i64 [ 1024, %vector.ph ], [ %avl.next, %vector.body ]
  %0 = call i32 @llvm.experimental.get.vector.length.i64(i64 %avl, i32 4, i1 true)
  %1 = getelementptr i8, ptr %a, i64 %index
  %vp.op.load = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 %1, <vscale x 4 x i1> splat (i1 true), i32 %0)
  %2 = zext <vscale x 4 x i8> %vp.op.load to <vscale x 4 x i32>
  %3 = getelementptr i8, ptr %b, i64 %index
  %vp.op.load1 = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 %3, <vscale x 4 x i1> splat (i1 true), i32 %0)
  %4 = zext <vscale x 4 x i8> %vp.op.load1 to <vscale x 4 x i32>
  %5 = mul <vscale x 4 x i32> %4, %2
  %6 = add <vscale x 4 x i32> %5, %vec.phi
  %7 = call <vscale x 4 x i32> @llvm.vp.merge.nxv4i32(<vscale x 4 x i1> splat (i1 true), <vscale x 4 x i32> %6, <vscale x 4 x i32> %vec.phi, i32 %0)
  %8 = zext i32 %0 to i64
  %current.iteration.next = add nuw i64 %8, %index
  %avl.next = sub nuw i64 %avl, %8
  %9 = icmp eq i64 %avl.next, 0
  br i1 %9, label %middle.block, label %vector.body, !llvm.loop !3

middle.block:                                     ; preds = %vector.body
  %10 = call i32 @llvm.vector.reduce.add.nxv4i32(<vscale x 4 x i32> %7)
  br label %for.exit

for.exit:                                         ; preds = %middle.block
  ret i32 %10
}

define i32 @vdot4asu(ptr %a, ptr %b) #0 {
entry:
  br label %vector.ph

vector.ph:                                        ; preds = %entry
  br label %vector.body

vector.body:                                      ; preds = %vector.body, %vector.ph
  %index = phi i64 [ 0, %vector.ph ], [ %current.iteration.next, %vector.body ]
  %vec.phi = phi <vscale x 4 x i32> [ zeroinitializer, %vector.ph ], [ %7, %vector.body ]
  %avl = phi i64 [ 1024, %vector.ph ], [ %avl.next, %vector.body ]
  %0 = call i32 @llvm.experimental.get.vector.length.i64(i64 %avl, i32 4, i1 true)
  %1 = getelementptr i8, ptr %a, i64 %index
  %vp.op.load = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 %1, <vscale x 4 x i1> splat (i1 true), i32 %0)
  %2 = zext <vscale x 4 x i8> %vp.op.load to <vscale x 4 x i32>
  %3 = getelementptr i8, ptr %b, i64 %index
  %vp.op.load1 = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 %3, <vscale x 4 x i1> splat (i1 true), i32 %0)
  %4 = sext <vscale x 4 x i8> %vp.op.load1 to <vscale x 4 x i32>
  %5 = mul <vscale x 4 x i32> %4, %2
  %6 = add <vscale x 4 x i32> %5, %vec.phi
  %7 = call <vscale x 4 x i32> @llvm.vp.merge.nxv4i32(<vscale x 4 x i1> splat (i1 true), <vscale x 4 x i32> %6, <vscale x 4 x i32> %vec.phi, i32 %0)
  %8 = zext i32 %0 to i64
  %current.iteration.next = add nuw i64 %8, %index
  %avl.next = sub nuw i64 %avl, %8
  %9 = icmp eq i64 %avl.next, 0
  br i1 %9, label %middle.block, label %vector.body, !llvm.loop !4

middle.block:                                     ; preds = %vector.body
  %10 = call i32 @llvm.vector.reduce.add.nxv4i32(<vscale x 4 x i32> %7)
  br label %for.exit

for.exit:                                         ; preds = %middle.block
  ret i32 %10
}

define i32 @vdot4asu2(ptr %a, ptr %b) #0 {
entry:
  br label %vector.ph

vector.ph:                                        ; preds = %entry
  br label %vector.body

vector.body:                                      ; preds = %vector.body, %vector.ph
  %index = phi i64 [ 0, %vector.ph ], [ %current.iteration.next, %vector.body ]
  %vec.phi = phi <vscale x 4 x i32> [ zeroinitializer, %vector.ph ], [ %7, %vector.body ]
  %avl = phi i64 [ 1024, %vector.ph ], [ %avl.next, %vector.body ]
  %0 = call i32 @llvm.experimental.get.vector.length.i64(i64 %avl, i32 4, i1 true)
  %1 = getelementptr i8, ptr %a, i64 %index
  %vp.op.load = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 %1, <vscale x 4 x i1> splat (i1 true), i32 %0)
  %2 = sext <vscale x 4 x i8> %vp.op.load to <vscale x 4 x i32>
  %3 = getelementptr i8, ptr %b, i64 %index
  %vp.op.load1 = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 %3, <vscale x 4 x i1> splat (i1 true), i32 %0)
  %4 = zext <vscale x 4 x i8> %vp.op.load1 to <vscale x 4 x i32>
  %5 = mul <vscale x 4 x i32> %4, %2
  %6 = add <vscale x 4 x i32> %5, %vec.phi
  %7 = call <vscale x 4 x i32> @llvm.vp.merge.nxv4i32(<vscale x 4 x i1> splat (i1 true), <vscale x 4 x i32> %6, <vscale x 4 x i32> %vec.phi, i32 %0)
  %8 = zext i32 %0 to i64
  %current.iteration.next = add nuw i64 %8, %index
  %avl.next = sub nuw i64 %avl, %8
  %9 = icmp eq i64 %avl.next, 0
  br i1 %9, label %middle.block, label %vector.body, !llvm.loop !5

middle.block:                                     ; preds = %vector.body
  %10 = call i32 @llvm.vector.reduce.add.nxv4i32(<vscale x 4 x i32> %7)
  br label %for.exit

for.exit:                                         ; preds = %middle.block
  ret i32 %10
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i32 @llvm.experimental.get.vector.length.i64(i64, i32 immarg, i1 immarg) #1

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: read)
declare <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr captures(none), <vscale x 4 x i1>, i32) #2

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare <vscale x 4 x i32> @llvm.vp.merge.nxv4i32(<vscale x 4 x i1>, <vscale x 4 x i32>, <vscale x 4 x i32>, i32) #1

; Function Attrs: nocallback nocreateundeforpoison nofree nosync nounwind speculatable willreturn memory(none)
declare i32 @llvm.vector.reduce.add.nxv4i32(<vscale x 4 x i32>) #3

attributes #0 = { "target-features"="+v,+experimental-zvdot4a8i" }
attributes #1 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
attributes #2 = { nocallback nofree nosync nounwind willreturn memory(argmem: read) }
attributes #3 = { nocallback nocreateundeforpoison nofree nosync nounwind speculatable willreturn memory(none) }

!0 = distinct !{!0, !1, !2}
!1 = !{!"llvm.loop.isvectorized", i32 1}
!2 = !{!"llvm.loop.unroll.runtime.disable"}
!3 = distinct !{!3, !1, !2}
!4 = distinct !{!4, !1, !2}
!5 = distinct !{!5, !1, !2}
